% FXNL_PIPELINE_02_ANALYZEDATA
% Functional-data analysis pipeline for processed BCI2000 recordings.
%
% Author: Frederik Lampert
% Institution: Mayo Clinic
% Year: 2026
%
% This script analyzes functional recordings extracted by
% fxnl_pipeline_01_extractData.m. It summarizes neural and task-related
% features from the processed MATLAB structures and generates analysis plots.
%
% Data availability:
%   Source recordings are available in BCI2000 .dat format through OpenNeuro:
%   doi:10.18112/openneuro.ds004624.v3.0.0
%
% Requirements:
%   - MATLAB R2023b
%   - Output from fxnl_pipeline_01_extractData.m
%   - Project-specific helper functions used in this analysis
%   - Any custom colormaps/toolboxes referenced below
%
% Before running:
%   1. Replace placeholder paths with local paths.
%   2. Review subject/file selections and analysis parameters.
%   3. Confirm that prerequisite processed data files have been generated.

clear all; close all; clc
addpath('/path/to/data/');
addpath('/path/to/data/');
addpath('/path/to/colormaps');
% Load KJM colormap
rwb = load('rwb_colormap.mat');
%% Configure paths
% Replace these placeholders with local paths before running the analysis.
projectPath = '/path/to/project/';
dataPath = '/path/to/data/';
dependencyPath = '/path/to/dependencies/';

addpath(genpath(projectPath));
addpath(genpath(dependencyPath));

%% Load processed data
% Load the MATLAB output generated by fxnl_pipeline_01_extractData.m. the functional data
[fname, fpth] = uigetfile(fullfile('/path/to/data/', '*.mat'), ...
    'Select the INPUT .mat FILE','MultiSelect','off');      % UI selectfile to open
load([fpth filesep fname]);

%% Specify path where to save figures
SAVE_FIG = 1;
fig_pth = '/path/to/figure_output_directory';

%% Select dog and parameters and 
sub = 'c01'; 

switch sub
    case 'c01'
        cnstrct = 'surface'; spec = 'vertical';  % Custom difference pair for cortec Grids
        knownBadChnls= [13,22];
        % Load the brain 
        brain = load('../../data/brainMAT/sub-c01_brain.mat');
        th=45; phi=-10;
        CameraUpVector = [-0.5,-0.8,-0.2];
        CameraViewAngle = 9;
    case 'c02'
        cnstrct = 'depth'; spec = 'D-S-D-S';
        knownBadChnls= [1:8];
        % Load the brain 
        brain = load('../../data/brainMAT/sub-c02_brain.mat');
    case 'c03'
        cnstrct = 'surface'; spec = 'horizontal';  % Custom difference pair for cortec Grids
        knownBadChnls= [11,21];
        % Load the brain 
        brain = load('../../data/brainMAT/sub-c03_brain.mat');
        th=270; phi=45;
        CameraUpVector = [0 0 1];
        CameraViewAngle = 7.7758;
    case 'c04'
        cnstrct = 'combined'; spec = 'G-G-D-S';
        knownBadChnls = 1:8;
        % Load the brain 
        brain = load('../../data/brainMAT/sub-c04_brain.mat');
    case 'c05'
        cnstrct = 'combined'; spec = 'G-G-G-D';
        knownBadChnls = [];
        brain = load('../../data/brainMAT/sub-c05_brain.mat');
        th=110; phi=50;
        CameraUpVector = [0 0 1];
        CameraViewAngle = 9;
end

%% Specify Constants 

% Specify if extracted from PREDEFINED StimulusCode or from MANUAL annotated Onsets
SC_type = 'StimulusCode' ;      % extracted from BCI2000 Stimulus Code
% SC_type = 'isPerformingTask' ;    % extracted from manualy annotated Onsets

% Select re-referencing
% REF_TYPE = 'None';
% REF_TYPE = 'BP';          % difference pair
% REF_TYPE = 'CAR';         % Common average
% REF_TYPE = 'leadMono'; RR_chnls = [1 9 17 25]
REF_TYPE = 'leadCAR';   % Custom difference pair for cortec Grids

HFB = [65:115 125:175];     % Specify broadband frequency range in Hz
LFB = [20:30];              % Specify low-frequency power band in Hz

% Specify p - treshold value
pthresh=.05;

% Specify Bonferoni correction use of
BF_correct = true;

%% Extract the data into the matrix
signal = [];
sc = [];
auxSignals = [];
fld_names = fieldnames(data);
SR = data.(fld_names{1}).SamplingRate;
baseline = [];
baselinePSD = [];
artifactMask = logical([]);
recStartIdx = [];
recNames = {};

for i = 1:length(fld_names)
    % Store start index and recording name
    recStartIdx(end+1,1) = size(signal,1) + 1;
    recNames{end+1,1} = fld_names{i};
    % Extract signal into mat
    nSamples = size(data.(fld_names{i}).Signal,1);
    signal = [signal ; data.(fld_names{i}).Signal];
    tempMask = false(nSamples ,1);
    % Extract artifact annotations if they exist
    if isfield(data.(fld_names{i}), 'Artifact') && isfield(data.(fld_names{i}).Artifact, 'MarkedEvents')
        if ~isempty(data.(fld_names{i}).Artifact.MarkedEvents)
            marked_idxs = data.(fld_names{i}).Artifact.MarkedEvents(:,2);
            marked_idxs = round(marked_idxs'.*SR);  % Ensure row vector
            for j = 1:2:(numel(marked_idxs)-1)
                % Keep indices within recording limits
                idxStart = max(1, marked_idxs(j));
                idxEnd   = min(nSamples, marked_idxs(j+1));
                if idxStart <= idxEnd
                    tempMask(idxStart:idxEnd) = true;         % Create artifact mask from start/end index pairs
                end
            end
        end
    end
    % Append mask corresponding to current recording
    artifactMask = [artifactMask; tempMask]; 

    % Extract cues into a vector if they exist
    if strcmp(SC_type,'isPerformingTask')
        sc = [sc; data.(fld_names{i}).(SC_type)];
        auxSignals = [auxSignals; data.(fld_names{i}).AnnotatedData];
        auxSigLabels = data.(fld_names{i}).AnnotatedDataLabels;  
    else
        sc = [sc; data.(fld_names{i}).(SC_type)];
    end
end
clear i

%% Check if the Stimulus Code and auxiliary signals are aligned
t_ax = (0:size(auxSignals,1)-1) / SR;
% Plot auxiliary signals
figure
ax = axes;
hold(ax,'on')
fontsize(ax, 16, 'points')
plot(ax, t_ax, auxSignals);

% Patch stimulus-code periods
patchEvents(ax, t_ax, sc);
% Patch artifact mask
patchEvents(ax, t_ax, artifactMask, [1 0 0]);

% Mark start of each recording
recStartTime = (recStartIdx - 1) / SR;
yl = ylim(ax);
for i = 1:numel(recStartTime)
    xline(ax, recStartTime(i), '--k', 'LineWidth', 1.2, 'HandleVisibility', 'off');
    t = text(ax, recStartTime(i),  yl(2), [recNames{i}], 'VerticalAlignment', 'top', ...
        'HorizontalAlignment', 'left', 'Interpreter', 'none', 'Rotation', 30);
    t.FontSize = 8;
end

legend(ax, auxSigLabels);
xlim(ax, 'tight');
xlabel(ax, 'Time (s)');

%% Re-reference data
switch REF_TYPE
    case 'None'
        ref_signal = signal;
        ch_names =  arrayfun(@(ch) sprintf('Ch %d', ch), 1:size(signal,2), 'UniformOutput', false);
        chs_names(bad_chnls) = arrayfun(@(n) sprintf('BAD-Ch %d', n), bad_chnls, 'UniformOutput', false);
    case 'BP'
        [ref_signal, ch_names] = custom_reref(signal,cnstrct,bad_chnls,REF_TYPE,spec);
    case 'leadMono'
        [ref_signal, ch_names] = custom_reref(signal,cnstrct,bad_chnls,REF_TYPE,RR_chnls);
    otherwise
        [ref_signal, ch_names] = custom_reref(signal,cnstrct,bad_chnls,REF_TYPE);
end

if strcmp(REF_TYPE, 'BP')
    good_ch = 1:size(ref_signal,2);
else
    good_ch = 1:32;          % Create a help x positions to perserve channel numbering in plots
    good_ch(bad_chnls) = []; % due to the removal of bad channels
end

%% Examine the channel variance
% Plot channel variance
vrnc1 = var(signal,0,1);
vrnc2 = var(ref_signal,0,1);
figure('Name','Signal Variance','Position', [400 150 1000 800])
plot(vrnc1, 'bo','LineWidth',1);
hold on
plot(good_ch,vrnc2(good_ch), 'ro', 'LineWidth',1);
plot(bad_chnls,mean(vrnc1(good_ch)),'kx', 'LineWidth',1.5)
xlabel('Channel no.'); ylabel('Variance'); legend({'Raw data'; 'Re-referenced'; 'Bad channels'})
ylim([0 prctile(vrnc1, 75)]); xticks(1:32); xlim([0 33]);
fontsize(16, 'points');
title('Functional task', 'Interpreter','none')
% axis square
if SAVE_FIG
    figname = [fig_pth filesep 'signal_variance.png'];
    saveas(gcf,figname);
end
clear vrnc1 vrnc2 temp

%% Visualize signals from trials
gain = 100; 
[tc_dur, tc] = runlength(sc, length(sc));
task_onsets = [1; cumsum(tc_dur(1:end-1)) + 1];

% Plot randomly selected rest trial
restTrials = find(tc == 0);
restTrialIdx = restTrials(randi([1 length(restTrials)]));
restSigIdx = task_onsets(restTrialIdx):(task_onsets(restTrialIdx)+tc_dur(restTrialIdx)-1); 
displayChannels(ref_signal(restSigIdx,:), SR, [],good_ch,gain, sprintf('Rest Trial #%d', restTrialIdx));
if strcmp(REF_TYPE, 'BP')
    yticklabels(fliplr(ch_names));
end
if SAVE_FIG
    figname = [fig_pth filesep 'restTrial'];
    print(gcf,figname,'-dpng','-r300')
    print(gcf,figname,'-dsvg','-vector')
end

% Plot randomly selected task trial
taskTrials = find(tc == 1);
taskTrialIdx = taskTrials(randi([1 length(taskTrials)]));
taskSigIdx = task_onsets(taskTrialIdx):(task_onsets(taskTrialIdx)+tc_dur(taskTrialIdx)-1); 
displayChannels(ref_signal(taskSigIdx,:), SR, [],good_ch,gain, sprintf('Task Trial #%d', taskTrialIdx))
if strcmp(REF_TYPE, 'BP')
    yticklabels(fliplr(ch_names));
end
if SAVE_FIG
    figname = [fig_pth filesep 'taskTrial'];
    print(gcf,figname,'-dpng','-r300')
    print(gcf,figname,'-dsvg','-vector')
end

clear restTrials taskTrials taskTrialIdx restTrialIdx task_onsets 

%%  Get rid of bad channels
if ~strcmp(REF_TYPE, 'BP')
    ref_signal(:,bad_chnls) = [];
    ch_names(:,bad_chnls) = [];
end

%% Calculate trial-by-trial spectra
% Specify frequency range for PSD calculation
window = hann(1*SR, 'periodic');        % Hann
nfft = length(window);
noverlap = floor(length(window) * 0.5);

% Specify frequency bands for statistical analysis
bands = struct( ...
        'delta', [1 4], ...
        'theta', [4 8], ...
        'alpha', [8 15], ...
        'beta', [15 30], ...
        'broadband', [65 150]);

trialSpectFeatures = trialSpectralFeatures(ref_signal, sc, SR, window, noverlap, nfft, bands);
clear bands window nfft noverlap

%% Browse spectrograms
% ref_signal(artifact_mask,:) = nan;
h = plotTrialSpectralBrowser(ref_signal, trialSpectFeatures, SR, ch_names);
% h.axTF.Colormap = colormap('jet'); % colormap(rgb.cm)
% h.axTF.CLim = [-15 15];
% colormap('jet')

%%  Display mean PSD acrosss all the channels ~~~~~~~~~~~~~~~~
PSDplot(trialSpectFeatures.meanPSD',trialSpectFeatures.freqBins,[],1)
axis square
if SAVE_FIG
    figname = [fig_pth filesep 'meanPSD'];
    print(gcf,figname,'-dpng','-r300')
    print(gcf,figname,'-dsvg','-vector')
end

%% Verify trials
channel_trialspect_browser(trialSpectFeatures.trialNormPSD,ch_names,[-5,5], 'Normalized power');
colormap(rgb.cm)

%% Remove bad trials if relevant
% Manually specify bad trials
bad_trials = [];
if ~isempty(bad_trials)
    fprintf('Marking trial %d as invalid\n', bad_trials)
    trialSpectFeatures.validTrial(bad_trials) = false;
end

%% Calculate statistics on spectra
spectStats = trialSpectralStats(trialSpectFeatures, LFB, HFB, BF_correct);
rvals = spectStats.rvals;

%% Plot distribution and r-values
% Plotting settings below reproduce the analysis figures and may be adapted as needed. distribution and Plot r-values
figure('Name','r2 activations', 'Position', [200 150 1300 800])
plot(good_ch, rvals.r_HFB.*(rvals.p_HFB<pthresh),'b*', 'LineWidth',2, 'MarkerSize',8)      % Plot r_HFB activations
hold on,
plot(good_ch, rvals.r_LFB.*(rvals.p_LFB<pthresh),'ro', 'LineWidth',2, 'MarkerSize',8)      % Plot r_LFB activations
plot(bad_chnls, zeros(size(bad_chnls)), 'kx', 'LineWidth',2, 'MarkerSize',8)              % Plot bad channels
plot(0:32,zeros(1,32+1), 'LineStyle','--', 'Color','k')
box off
xlim([0 32])
xlabel('electrode number'),ylabel('r^2')
legend('HFB','LFB', 'Bad Channels')
title('r^2 activation values')


%% R2 values heatmap
figure('Name','r2 activations', 'Position', [200 150 1300 800])
imagesc(rvals.rmap); 
colormap(rwb.cm), colorbar
ax = gca;
set(ax,'clim',max(abs(ax.CLim))*[-1 1])
title('r^2 featuremap')
subtitle(sprintf('r^2 max = %d for %s',max(rvals.r_HFB), ch_names{find(rvals.r_HFB==max(rvals.r_HFB))}))
xlabel('Frequency (Hz)'), ylabel('Channel')
if strcmp(REF_TYPE, 'BP')
    set(ax,'YTick', 1:size(rvals.rmap,1),'YTickLabel', ch_names)
else
    set(ax,'YTick', 1:length(good_ch),'YTickLabel', good_ch)
end

fontsize(16,'points')

%% Find significant responses and plot channel PSDs

activeCh=find(rvals.p_HFB<pthresh);
for k=activeCh  
    disp([ch_names{k} ':: r^2=' num2str(rvals.r_HFB(k))  ', p=' num2str(rvals.p_HFB(k)) ' // r^2=' num2str(rvals.r_LFB(k))  ', p=' num2str(rvals.p_LFB(k))])
end

% Plot all spectra andhighligh the significant r
ps = trialSpectFeatures.trialPSD(:,:,trialSpectFeatures.validTrial);
tr_sc = trialSpectFeatures.trialStimCode(trialSpectFeatures.validTrial);
for k=1:size(ps,2)
    figure('Position', [200 150 1300 800])
    semilogy(mean(ps(:,k,tr_sc==0),3,'omitnan'),'b'), hold on
    semilogy(mean(ps(:,k,tr_sc==1),3,'omitnan'),'r'), hold on
    % title(['Channel ' num2str(good_ch(k))])
    title(ch_names(k))     % For BP reref
    if ismember(k,activeCh)
        subtitle(['HFB r^2=' num2str(rvals.r_HFB(k))  ', HFB p=' num2str(rvals.p_HFB(k)) ' // LFB r^2=' num2str(rvals.r_LFB(k))  ', LFB p=' num2str(rvals.p_LFB(k))], ...
            'Color','red', 'FontWeight','bold')
    else
        subtitle(['HFB r^2=' num2str(rvals.r_HFB(k))  ', HFB p=' num2str(rvals.p_HFB(k)) ' // LFB r^2=' num2str(rvals.r_LFB(k))  ', LFB p=' num2str(rvals.p_LFB(k))])
    end
    xlim('tight')
    legend({'Rest';'Task'})
    ylabel('Power \muV^2 / Hz')
    xlabel('Frequency (Hz)')
    fontsize(16,'points')
    axis square

    % Save Figures
    if SAVE_FIG
        figname = sprintf([fig_pth filesep 'ch%d_PSD.png'],k);
        saveas(gcf,figname);
    end
end

%% Plot the rval distribution for active channels
nps = trialSpectFeatures.trialNormPSD(:,:,trialSpectFeatures.validTrial);
for j=activeCh  
    ch_nps = squeeze(nps(HFB,j,:));
    ch_BB_avg = mean(ch_nps,1);

    figure('Position', [200 150 1300 800])
    gscatter(1:numel(tr_sc),ch_BB_avg,tr_sc)
    title(ch_names(j))
    subtitle(['HFB r^2=' num2str(rvals.r_HFB(j))  ', HFB p=' num2str(rvals.p_HFB(j)) ' // LFB r^2=' num2str(rvals.r_LFB(j))  ', LFB p=' num2str(rvals.p_LFB(j))])
    legend({'Rest';'Task'})
    ylabel(sprintf('Normalized Power, %d-%d Hz' , HFB(1),HFB(end)))
    xlabel('Trial number')
    xlim("tight")
    fontsize(16,'points')

    % Save Figures
    if SAVE_FIG
        figname = sprintf([fig_pth filesep 'ch%d_rval_dist.png'],j);
        saveas(gcf,figname);
    end
end

%% Plot the  channel locations on the brain
if strcmp(REF_TYPE, 'BP')
    plt_locs = getBipolarLocs(plt_locs,ch_names);
    bad_chnls = [];
end

plot_offset = 0.05;  msize = 20;

figure('Position', [200 150 1300 800]) 
ctmr_surf(brain.cortex,1,cm)
label_add_popout(plt_locs,[], plot_offset,msize)
% loc_view(th,phi);
set(gcf,'color','w')

camup(CameraUpVector)
camva(CameraViewAngle)

%%  Plot r2 values on top of the brain     
rH=rvals.r_HFB;
rL=rvals.r_LFB;

% HFB
f1=figure('Position', [200 150 1300 800],'Name','HFB');
ctmr_gauss_plot(brain.cortex,[0 0 0],0)
add_activation_popout_w_sig(plt_locs, bad_chnls, rH, rvals.p_HFB<pthresh, th, phi)
set(gcf,'color','w')
loc_view(th,pi)
% camup(CameraUpVector)
% camva(CameraViewAngle)
title('HFB')
figname = sprintf([fig_pth filesep dog '_HFB_brain']);
print(gcf,figname,'-dpng','-r300')

%LFB
f2=figure('Position', [200 150 1300 800],'Name','LFB');
ctmr_gauss_plot(brain.cortex,[0 0 0],0)
add_activation_popout_w_sig(plt_locs, bad_chnls, rL, rvals.p_HFB<pthresh, th, phi)
set(gcf,'color','w')
loc_view(th,pi)
% camup(CameraUpVector)
% camva(CameraViewAngle)
title('LFB')
figname = sprintf([fig_pth filesep dog '_LFB_brain']);
print(gcf,figname,'-dpng','-r300')

%% Helper functions
function badChannels = getBadCh(dataStruct)
    badChannels = [];
    flnames = fieldnames(dataStruct);
    for i = 1:numel(flnames)
        badChannels = [badChannels, dataStruct.(flnames{i}).BadChannels];
    end
    badChannels = unique(badChannels);
end
